[package]
name = "minimessage-rs"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "minimessage text formatting for Pumpkin Minecraft server plugins"
repository = "https://github.com/Mettwasser/minimessage-rs"
homepage = "https://github.com/Mettwasser/minimessage-rs"


[dependencies]
minimessage-impl = { path = "./minimessage-impl", version = "0.1.1" }
minimessage-macro = { path = "./minimessage-macro", version = "0.1.1" }
minimessage-runtime = { path = "./minimessage-runtime", version = "0.1.1" }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "parser"
harness = false

[workspace]
members = [
    "minimessage-macro",
    "minimessage-impl",
    "minimessage-runtime",
    "minimessage-rt-compat",
]

[lints.clippy]
"missing_errors_doc" = "allow"
"pedantic" = { level = "warn", priority = -1 }

[patch.crates-io]
minimessage-runtime = { path = "minimessage-runtime" }
minimessage-impl = { path = "minimessage-impl" }
minimessage-macro = { path = "minimessage-macro" }
