[package]
name = "minimessage-runtime"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Runtime minimessage deserialization for Pumpkin Minecraft server plugins"
repository = "https://github.com/Mettwasser/minimessage-rs"
homepage = "https://github.com/Mettwasser/minimessage-rs"

[dependencies]
minimessage-impl = { version = "0.1.0", path = "../minimessage-impl" }
pumpkin-plugin-api = { version = "0.1.0", git = "https://github.com/Pumpkin-MC/Pumpkin" }
thiserror = "2.0.20"
